version: '3.7'

volumes:
  supercalc:
    driver: local
  mysql:
    driver: local
  mysql_data: {}

services:
  mysql:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      -  ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass

  gitea:
    image: gitea/gitea:1.18.5
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=mysqldb
      - GITEA__database__USER=mysqluser
      - GITEA__database__PASSWD=mysqlpass
    restart: always
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - mysql
  supercalc:
    image: donetian/supercalc
    container_name: supercalc
    volumes:
      - supercalc:/var/html/www
    ports:
      - "8080:80"
