global:
  scrape_interval: 15s  # How frequently to scrape targets

scrape_configs:
  - job_name: network-1
    static_configs:
      - targets:
        - pipelines:9100  # Example: replace with actual IP or DNS name

  - job_name: network-2
    static_configs:
      - targets:
        - containers:9100
